spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.template.default-topic=medicine-stock-events

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices_sessionte_kafka_pharmacy_db
spring.datasource.username=postgres
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huongcaoha1s9s@gmail.com
spring.mail.password=zego ydec dzzi wkzy
spring.mail.properties.smtp.auth=true
spring.mail.properties.smtp.starttls.enable=true
spring.mail.properties.smtp.timeout=5000